/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CivitasJuego;

import civitas.OperacionesJuego;
import javax.swing.JOptionPane;

/**
 *
 * @author juliocamposrodriguez
 */
public class CivitasView extends javax.swing.JFrame {
    
    CivitasJuego juego;
    JugadorPanel jugadorPanel;
    GestionarDialog gestionarD;
    
   /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        
        gestionarD = new GestionarDialog(this);
        
        jugadorPanel = new JugadorPanel();
        
        contenedorVistaJugador.add(jugadorPanel);
        
        repaint();
        
        revalidate();
    }
    
    public void setCivitasJuego(CivitasJuego game){
        juego = game;
        setVisible(true);
    }
    
    public void actualizarVista(){
        jugadorPanel.setJugador(juego.getJugadorActual());
        
        texto_casilla.setText(juego.getCasillaActual().toString());
        
        panel_ranking.setVisible(false);
        
        ranking.setVisible(false);
        
        area_ranking.setVisible(false);
        
        if (juego.finalDelJuego()){
            
            panel_ranking.setVisible(true);
            ranking.setVisible(true);
            area_ranking.setVisible(true);
            
            String rank = juego.mostrar_ranking();
            
            area_ranking.setText(rank);
        }
        
        repaint();
        
        revalidate();
    }
    
    public void mostrarSiguienteOperacion(OperacionesJuego operacion){
        
        texto_operacion.setText(operacion.toString());
        
        actualizarVista();
    }
    
    void mostrarEventos(){
        DiarioDialog diarioD = new DiarioDialog(this);
    }
    
    public Respuestas comprar(){
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        
        if (opcion==0)
            return Respuestas.SI;
        else
            return Respuestas.NO;
    }
    
    public SalidasCarcel salirCarcel(){
        String[] opciones = {"Pagando", "Tirando"};
        
        int respuesta = JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la carcel?", "Salir de la carcel", 
                JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        
        if (respuesta == 0)
            return SalidasCarcel.PAGANDO;
        else
            return SalidasCarcel.TIRANDO;
    }
    
    public int getGestion(){
        return gestionarD.getGestion();
    }
    
    public int getPropiedad(){
        return gestionarD.getPropiedad();
    }
    
    public void gestionar(){
        gestionarD.gestionar(juego.getJugadorActual());
        
        pack();
        repaint();
        revalidate();
        
        gestionarD.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        siguiente_operacion = new javax.swing.JLabel();
        texto_operacion = new javax.swing.JTextField();
        ranking = new javax.swing.JLabel();
        panel_ranking = new javax.swing.JScrollPane();
        area_ranking = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto_casilla = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Titulo.setText("CivitasJuego");
        Titulo.setEnabled(false);

        siguiente_operacion.setText("Siguiente operación");
        siguiente_operacion.setEnabled(false);

        texto_operacion.setEnabled(false);
        texto_operacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_operacionActionPerformed(evt);
            }
        });

        ranking.setText("Ranking");

        area_ranking.setColumns(20);
        area_ranking.setRows(5);
        panel_ranking.setViewportView(area_ranking);

        texto_casilla.setColumns(20);
        texto_casilla.setRows(5);
        jScrollPane1.setViewportView(texto_casilla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(panel_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(ranking))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(siguiente_operacion)
                        .addGap(48, 48, 48)
                        .addComponent(texto_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente_operacion)
                    .addComponent(texto_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(ranking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_operacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_operacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_operacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextArea area_ranking;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane panel_ranking;
    private javax.swing.JLabel ranking;
    private javax.swing.JLabel siguiente_operacion;
    private javax.swing.JTextArea texto_casilla;
    private javax.swing.JTextField texto_operacion;
    // End of variables declaration//GEN-END:variables
}
